"""empty message

Revision ID: b53b383e8cb9
Revises: cd50465b5bce
Create Date: 2021-10-11 20:46:15.842705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53b383e8cb9'
down_revision = 'cd50465b5bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'keywords')
    # ### end Alembic commands ###
